"""Event names accepted by ``update_on``, generated from the AG Grid types.

Do not edit by hand. Regenerate with::

    python scripts/gen_event_catalog.py

Generated from ag-grid-community 35.3.0, the version pinned in
src/st_aggrid/frontend/package.json. CI runs the generator with ``--check``, so
this file cannot drift from the bundled AG Grid without failing the build.
"""

# The ag-grid-community release these names were read from. Reported in the
# warning text so a user who hits it can tell which catalog was consulted.
AG_GRID_VERSION = "35.3.0"

# _PUBLIC_EVENTS: what api.addEventListener publicly supports, and therefore
# exactly what update_on may name.
GRID_EVENTS = frozenset(
    {
        "advancedFilterBuilderVisibleChanged",
        "asyncTransactionsFlushed",
        "batchEditingStarted",
        "batchEditingStopped",
        "bodyScroll",
        "bodyScrollEnd",
        "bulkEditingStarted",
        "bulkEditingStopped",
        "cellClicked",
        "cellContextMenu",
        "cellDoubleClicked",
        "cellEditRequest",
        "cellEditingStarted",
        "cellEditingStopped",
        "cellFocused",
        "cellKeyDown",
        "cellMouseDown",
        "cellMouseOut",
        "cellMouseOver",
        "cellSelectionChanged",
        "cellSelectionDeleteEnd",
        "cellSelectionDeleteStart",
        "cellValueChanged",
        "chartCreated",
        "chartDestroyed",
        "chartOptionsChanged",
        "chartRangeSelectionChanged",
        "columnEverythingChanged",
        "columnGroupOpened",
        "columnHeaderClicked",
        "columnHeaderContextMenu",
        "columnHeaderMouseLeave",
        "columnHeaderMouseOver",
        "columnMenuVisibleChanged",
        "columnMoved",
        "columnPinned",
        "columnPivotChanged",
        "columnPivotModeChanged",
        "columnResized",
        "columnRowGroupChanged",
        "columnValueChanged",
        "columnVisible",
        "columnsReset",
        "componentStateChanged",
        "contextMenuVisibleChanged",
        "cutEnd",
        "cutStart",
        "displayedColumnsChanged",
        "dragCancelled",
        "dragStarted",
        "dragStopped",
        "expandOrCollapseAll",
        "fillEnd",
        "fillStart",
        "filterChanged",
        "filterModified",
        "filterOpened",
        "filterUiChanged",
        "findChanged",
        "firstDataRendered",
        "floatingFilterUiChanged",
        "gridColumnsChanged",
        "gridPreDestroyed",
        "gridReady",
        "gridSizeChanged",
        "headerFocused",
        "modelUpdated",
        "newColumnsLoaded",
        "paginationChanged",
        "pasteEnd",
        "pasteStart",
        "pinnedRowDataChanged",
        "pinnedRowsChanged",
        "pivotMaxColumnsExceeded",
        "rangeDeleteEnd",
        "rangeDeleteStart",
        "rangeSelectionChanged",
        "redoEnded",
        "redoStarted",
        "rowClicked",
        "rowDataUpdated",
        "rowDoubleClicked",
        "rowDragCancel",
        "rowDragEnd",
        "rowDragEnter",
        "rowDragLeave",
        "rowDragMove",
        "rowEditingStarted",
        "rowEditingStopped",
        "rowGroupOpened",
        "rowResizeEnded",
        "rowResizeStarted",
        "rowSelected",
        "rowValueChanged",
        "selectionChanged",
        "sortChanged",
        "stateUpdated",
        "storeRefreshed",
        "toolPanelSizeChanged",
        "toolPanelVisibleChanged",
        "tooltipHide",
        "tooltipShow",
        "undoEnded",
        "undoStarted",
        "viewportChanged",
        "virtualColumnsChanged",
        "virtualRowRemoved",
    }
)

# Real event names that fire on a Column instance rather than the grid api, so
# update_on can never receive them. Names that are also grid events (sortChanged,
# columnValueChanged and friends) are excluded: those are valid update_on values.
COLUMN_ONLY_EVENTS = frozenset(
    {
        "colDefChanged",
        "columnStateUpdated",
        "filterActiveChanged",
        "firstRightPinnedChanged",
        "formulaRefChanged",
        "headerHighlightChanged",
        "lastLeftPinnedChanged",
        "leftChanged",
        "menuVisibleChanged",
        "movingChanged",
        "visibleChanged",
        "widthChanged",
    }
)

# The same, for events dispatched on a RowNode. rowSelected is absent because it
# is also a grid event.
ROW_NODE_ONLY_EVENTS = frozenset(
    {
        "allChildrenCountChanged",
        "cellChanged",
        "childIndexChanged",
        "dataChanged",
        "displayedChanged",
        "draggingChanged",
        "expandedChanged",
        "firstChildChanged",
        "groupChanged",
        "hasChildrenChanged",
        "heightChanged",
        "lastChildChanged",
        "masterChanged",
        "mouseEnter",
        "mouseLeave",
        "rowHighlightChanged",
        "rowIndexChanged",
        "rowPinned",
        "selectableChanged",
        "topChanged",
        "uiLevelChanged",
    }
)

# _INTERNAL_EVENTS. AgEventType unions these with the public set and the event
# service does not validate names, so listening for one very likely does work
# today. They are still not supportable: GridApi.addEventListener is typed to the
# public set and AG Grid marks these removable without notice. Telling a caller
# such a name "is not an AG Grid event" would be false, so it gets its own
# message.
INTERNAL_EVENTS = frozenset(
    {
        "advancedFilterEnabledChanged",
        "alignedGridColumn",
        "alignedGridScroll",
        "bodyHeightChanged",
        "cellEditValuesChanged",
        "cellFocusCleared",
        "chartTitleEdit",
        "checkboxChanged",
        "columnContainerWidthChanged",
        "columnGroupHeaderHeightChanged",
        "columnHeaderHeightChanged",
        "columnHoverChanged",
        "columnPanelItemDragEnd",
        "columnPanelItemDragStart",
        "dataTypesInferred",
        "displayedColumnsWidthChanged",
        "displayedRowsChanged",
        "fieldPickerValueSelected",
        "fieldValueChanged",
        "filterClosed",
        "filterDestroyed",
        "filterHandlerDestroyed",
        "filterSwitched",
        "flashCells",
        "fullWidthRowFocused",
        "gridOptionsChanged",
        "headerHeightChanged",
        "headerRowsChanged",
        "heightScaleChanged",
        "keyShortcutChangedCellEnd",
        "keyShortcutChangedCellStart",
        "leftPinnedWidthChanged",
        "overlayExclusiveChanged",
        "paginationPixelOffsetChanged",
        "pinnedHeightChanged",
        "recalculateRowBounds",
        "richSelectListRowSelected",
        "rightPinnedWidthChanged",
        "rowContainerHeightChanged",
        "rowCountReady",
        "rowDataUpdateStarted",
        "rowDragVisibilityChanged",
        "rowExpansionStateChanged",
        "rowNodeDataChanged",
        "scrollGapChanged",
        "scrollVisibilityChanged",
        "scrollbarWidthChanged",
        "showRowGroupColsSetChanged",
        "sideBarUpdated",
        "stickyTopOffsetChanged",
        "storeUpdated",
        "stylesChanged",
        "suppressFieldDotNotation",
        "suppressMenuHide",
        "suppressMovableColumns",
    }
)
